
project_id = "wwakwpvaszfrwunybuou"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[functions.get-subscription-plans]
verify_jwt = true
