
project_id = "wwakwpvaszfrwunybuou"

[auth]
# Set OTP expiration to 30 minutes (1800 seconds) for improved security
otp_exp = 1800

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[functions.get-subscription-plans]
verify_jwt = true
