// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwakwpvaszfrwunybuou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3YWt3cHZhc3pmcnd1bnlidW91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NDg3NDIsImV4cCI6MjA2MDUyNDc0Mn0.8f0BZWK4UC5NPYDcenEEpv0IGU1eF0HsDXs4TM0DL04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);